---
title: "Validation of interpolation method"
author: "Antonio J. Perez-Luque"
date: "12/6/2018"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(raster)
library(rasterVis)
library(gstat)
library(here)
here()
```

```{r}
# Load data
orig_data <- raster('/Users/ajpeluLap/Desktop/tas_day_MIROC-ESM_lgm_r1i1p1_46000101-46991231.nc')

orig_data <- stack(orig_data)

levelplot(orig_data)
```



# Interpolation

Prepare the data
```{r}
# Load interpolate function 
devtools::source_url("https://raw.githubusercontent.com/macroecology/BioExtremes/interpolation/interpolate.R") 

#Create a grid 
# Use ./masking.R


m <- create_mask(0.5, "land")
mr <- as(m, "SpatialPixelsDataFrame")
class(mr)
# plot(as(mr, "SpatialPolygons"))


# Centroids of the cells 
# See https://gis.stackexchange.com/questions/268091/centroids-of-each-grid-cell
grid_centroids <- coordinates(mr) 
centers <- SpatialPoints(grid_centroids, proj4string = CRS(projection(mr)))
# plot(centers, add = TRUE, col='red', pch = 20)


our_grid <- as.data.frame(centers@coords)
```

Run the interpolation 
```{r}
start_time <- Sys.time()
i <- clim.interpolate(orig_data, our_grid, imethod = spline)
end_time <- Sys.time()
end_time - start_time
```


```{r}
# Plot the orginal 
plot(orig_data)

# Plot the interpolation 
ri <- rasterFromXYZ(i)
levelplot(ri)



plot(ri)




















centers<- SpatialPoints(grid_center, proj4string = CRS(wgs.84))
plot(centers,add=T, col='red', pch=20)




cs = 10.0 # grid cell size 
worldMap <- as( raster::extent(-180, 180, -90, 90), "SpatialPolygons") # Extent of grid to SpatialPolygons
wgs.84 <- "+proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0"
proj4string(worldMap) <- crs(wgs.84) 
class(worldMap)
plot(worldMap)
ras <- raster(worldMap, resolution = cs) # Create raster using the extent 
ras[] <- 1:ncell(ras)
cat("\n", "Number of cells in raster: ", ncell(ras), "\n")  
mw <- as(ras, "SpatialPixelsDataFrame")
class(mw)
plot( as(mw, "SpatialPolygons") )

grid_center <- coordinates(mw) #Determine centroids of grid cells 
centers<- SpatialPoints(grid_center, proj4string = CRS(wgs.84))
plot(centers,add=T, col='red', pch=20)






```






validation.data <- data.frame(rnorm(10, mean = 0.2, sd = 1))
obs.pred <- data.frame(y=dat$y, krig=predict(krig.fit),
                       tps=predict(tps.fit) )


```


# Validation of Spatial Interpolation 
- Cross-validation method: subsetting the original point data in two dataset, *calibration* and *validation* 



We can use 

